name: PHPUnit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2]
        laravel: [10.*, 11.*]
        phpunit-versions: ['10.1']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
        tools: phpunit:${{ matrix.phpunit-versions }}
        coverage: none

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" --no-update --no-interaction --prefer-dist
        composer install --prefer-dist --no-interaction --no-suggest

    - name: Run tests
      run: composer run-script test
