name: PHPUnit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.2'
            laravel: '10.*'
            phpunit-versions: '10.1'
          - php: '8.2'
            laravel: '11.*'
            phpunit-versions: '10.1'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
        tools: phpunit:${{ matrix.phpunit-versions }}
        coverage: none

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" --no-update --no-interaction --prefer-dist
        composer install --prefer-dist --no-interaction --no-suggest

    - name: Run tests
      run: composer run-script test
