name: Style Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Install dependencies
        run:  composer update --prefer-stable --no-interaction

      - name: Run script
        run: vendor/bin/pint --test
